<?xml version="1.0" encoding="utf-8"?><Database Name="PLANXAPP" Class="ConexionLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\BrandonZamora;Initial Catalog=PLANXAPP;Integrated Security=True;Encrypt=False" SettingsObjectName="PlanXBackend.Properties.Settings" SettingsPropertyName="PLANXAPPConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SP_ACTUALIZAR_EVENTO" Method="SP_ACTUALIZAR_EVENTO">
    <Parameter Name="TITULO" Parameter="tITULO" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="COD_INVI" Parameter="cOD_INVI" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_REGISTRO_USUARIO_REGULAR" Method="SP_REGISTRO_USUARIO_REGULAR">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="APELLIDOS" Parameter="aPELLIDOS" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="CODPAIS" Parameter="cODPAIS" Type="System.String" DbType="NVarChar(2)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_TAREA" Method="SP_ACTUALIZAR_TAREA">
    <Parameter Name="TITULO" Parameter="tITULO" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_TAREA" Parameter="iD_TAREA" Type="System.Int32" DbType="Int" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_USUARIO_REGULAR" Method="SP_ACTUALIZAR_USUARIO_REGULAR">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CONTRA_ANTIGUA" Parameter="cONTRA_ANTIGUA" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="CONTRA_NUEVA" Parameter="cONTRA_NUEVA" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ELIMINAR_EVENTO" Method="SP_ELIMINAR_EVENTO">
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="COD_INV" Parameter="cOD_INV" Type="System.String" DbType="NVarChar(6)" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ELIMINAR_TAREA" Method="SP_ELIMINAR_TAREA">
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID_TAREA" Parameter="iD_TAREA" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ELIMINAR_USUARIO_REGULAR" Method="SP_ELIMINAR_USUARIO_REGULAR">
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_EVENTO" Method="SP_INSERTAR_EVENTO">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="FECHORA_INICIO" Parameter="fECHORA_INICIO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FECHORA_FIN" Parameter="fECHORA_FIN" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LIMITE_USUARIO" Parameter="lIMITE_USUARIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="DURACION" Parameter="dURACION" Type="System.Double" DbType="Float" />
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_TAREA" Method="SP_INSERTAR_TAREA">
    <Parameter Name="TITULO" Parameter="tITULO" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="FECHORA_INICIO" Parameter="fECHORA_INICIO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FECHORA_FIN" Parameter="fECHORA_FIN" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="PRIORIDAD" Parameter="pRIORIDAD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_LOGIN" Method="SP_LOGIN">
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="id_usuario" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="nombre" Type="System.String" DbType="NVarChar(50)" Direction="InOut" />
    <Parameter Name="apellidos" Type="System.String" DbType="NVarChar(50)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_OBTENER_EVENTO" Method="SP_OBTENER_EVENTO">
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="COD_INVI" Parameter="cOD_INVI" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="FECINICIO" Parameter="fECINICIO" Type="System.DateTime" DbType="DateTime" Direction="InOut" />
    <Parameter Name="FECFIN" Parameter="fECFIN" Type="System.DateTime" DbType="DateTime" Direction="InOut" />
    <Parameter Name="LIM_USERS" Parameter="lIM_USERS" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="DURACION" Parameter="dURACION" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_OBTENER_TAREA" Method="SP_OBTENER_TAREA">
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="TITULO" Parameter="tITULO" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="VarChar(255)" Direction="InOut" />
    <Parameter Name="FECINICIO" Parameter="fECINICIO" Type="System.DateTime" DbType="DateTime" Direction="InOut" />
    <Parameter Name="FECFIN" Parameter="fECFIN" Type="System.DateTime" DbType="DateTime" Direction="InOut" />
    <Parameter Name="ID_PRIORIDAD" Parameter="iD_PRIORIDAD" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_REGISTRO_EVENTO_INVITADO" Method="SP_REGISTRO_EVENTO_INVITADO">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="VarChar(255)" />
    <Parameter Name="COD_INVI" Parameter="cOD_INVI" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="FEC_INICIO" Parameter="fEC_INICIO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FEC_FIN" Parameter="fEC_FIN" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_REGISTRO_EVENTO_REGULAR" Method="SP_REGISTRO_EVENTO_REGULAR">
    <Parameter Name="ID_USER" Parameter="iD_USER" Type="System.Int32" DbType="Int" />
    <Parameter Name="COD_INVI" Parameter="cOD_INVI" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="FEC_INICIO" Parameter="fEC_INICIO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FEC_FIN" Parameter="fEC_FIN" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>